# Define reusable common headers for HTTP requests
common_headers: &common_headers
  Content-Type: application/json
  Accept: application/json

# Define reusable common body parameters
common_body: &common_body
  someProperty: someValue
  userid_resolve: { $dynamic: user_structured }
  userid_request: { $dynamic: user_structured, when: request}

dynamics:
  patterns:
    user_structured:
      template: "1234${hex:22}${choice:teams}00"
    user_name:
      template: "user-${alpha:6}"
  sets:
    teams: ["00","01","02","03"]

StashConfig:
  # Unique name to identify this configuration
  Name: Example

  # Default settings applied to all requests unless overridden
  Defaults:
    URLRoot: https://api.restful-api.dev # Open Test API endpoint
    FlowControl:
      DelaySeconds: 2
      TimeoutSeconds: 2

    # Disable TLS certificate verification
    InsecureTLS: true

    # Default headers including common headers
    Headers:
      <<: *common_headers
      Authorization: Bearer ABC123

    # Retry configuration for failed requests
    Retry:
      Attempts: 4                    # Number of retry attempts
      BackoffStrategy: exponential   # Exponential backoff between retries
      BackoffSeconds: 0.5            # Initial backoff duration
      Multiplier: 2.0                # Multiplier for exponential backoff
      MaxBackoffSeconds: 10          # Maximum backoff duration
      Jitter: true                   # Add randomness to backoff time
      RetryOnStatus: [ 429, 500, 502, 503, 504 ]  # HTTP status codes to retry on

  # Forced settings that override request-specific settings
  Forced:
    Headers:
      Authorization: Bearer DEF456
    Body:
      <<: *common_body

  # Define sequences of API requests
  Sequences:
    - Name: ExampleSeq             # Name of the sequence
      Type: Sequential             # Requests run in sequence
      Requests:
        - GetObject_7: # First request
            Method: GET            # HTTP method
            URLPath: /objects/7    # API endpoint path
            Body: # Request body
              someOther: value2
              timestamp_resolve_time: { $timestamp: epoch_ms }
              timestamp_request_time: { $timestamp: { format: epoch_ms, when: request } }
              username: { $dynamic: user_name }
            Retry: Null           # Disable retry for this request
        - GetObjects_3_5_10: # Second request
            Method: GET
            URLPath: /objects
            Query:
              id:
              - 3
              - 5
              - 10
    - Name: ConcurrentSeq          # Name of the sequence
      Type: Concurrent             # Requests run concurrently
      ConcurrencyLimit: 4
      Requests:
        - GetObject_7: # First request
            Method: GET            # HTTP method
            URLPath: /objects/7    # API endpoint path
            Body: # Request body
              someOther: value2
              timestamp_resolve_time: { $timestamp: epoch_ms }
              timestamp_request_time: { $timestamp: { format: epoch_ms, when: request } }
              username: { $dynamic: user_name }
            Retry: Null           # Disable retry for this request
        - GetObject_3: # First request
            Method: GET            # HTTP method
            URLPath: /objects/3    # API endpoint path
            Body: # Request body
              someOther: value2
              timestamp_resolve_time: { $timestamp: epoch_ms }
              timestamp_request_time: { $timestamp: { format: epoch_ms, when: request } }
              username: { $dynamic: user_name }
            Retry: Null           # Disable retry for this request
        - GetObject_5: # First request
            Method: GET            # HTTP method
            URLPath: /objects/5    # API endpoint path
            Body: # Request body
              someOther: value2
              timestamp_resolve_time: { $timestamp: epoch_ms }
              timestamp_request_time: { $timestamp: { format: epoch_ms, when: request } }
              username: { $dynamic: user_name }
        - GetObject_10: # First request
            Method: GET            # HTTP method
            URLPath: /objects/10    # API endpoint path
            Body: # Request body
              someOther: value2
              timestamp_resolve_time: { $timestamp: epoch_ms }
              timestamp_request_time: { $timestamp: { format: epoch_ms, when: request } }
              username: { $dynamic: user_name }
            Retry: Null           # Disable retry for this request
